package Model;
// Generated 26-jul-2017 17:58:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String codcliente;
     private String nombres;
     private String apellidos;
     private String direccion;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(String codcliente) {
        this.codcliente = codcliente;
    }
    public Cliente(String codcliente, String nombres, String apellidos, String direccion, Set<Factura> facturas) {
       this.codcliente = codcliente;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.facturas = facturas;
    }
   
    public String getCodcliente() {
        return this.codcliente;
    }
    
    public void setCodcliente(String codcliente) {
        this.codcliente = codcliente;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


