package Model;
// Generated 22-jul-2017 17:32:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Comision generated by hbm2java
 */
public class Comision  implements java.io.Serializable {


     private BigDecimal codigo;
     private Vendedor vendedor;
     private BigDecimal saldo;
     private Date fecha;

    public Comision() {
    }

	
    public Comision(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Comision(BigDecimal codigo, Vendedor vendedor, BigDecimal saldo, Date fecha) {
       this.codigo = codigo;
       this.vendedor = vendedor;
       this.saldo = saldo;
       this.fecha = fecha;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


