package Model;
// Generated 16-jul-2017 13:53:14 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura  implements java.io.Serializable {


     private BigDecimal coddetalle;
     private Producto producto;
     private Factura factura;
     private Servicio servicio;
     private BigDecimal cantidad;
     private BigDecimal totalDetalle;
     private BigDecimal precioRealUnidad;

    public DetalleFactura() {
    }

	
    public DetalleFactura(BigDecimal coddetalle) {
        this.coddetalle = coddetalle;
    }
    public DetalleFactura(BigDecimal coddetalle, Producto producto, Factura factura, Servicio servicio, BigDecimal cantidad, BigDecimal totalDetalle, BigDecimal precioRealUnidad) {
       this.coddetalle = coddetalle;
       this.producto = producto;
       this.factura = factura;
       this.servicio = servicio;
       this.cantidad = cantidad;
       this.totalDetalle = totalDetalle;
       this.precioRealUnidad = precioRealUnidad;
    }
   
    public BigDecimal getCoddetalle() {
        return this.coddetalle;
    }
    
    public void setCoddetalle(BigDecimal coddetalle) {
        this.coddetalle = coddetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getTotalDetalle() {
        return this.totalDetalle;
    }
    
    public void setTotalDetalle(BigDecimal totalDetalle) {
        this.totalDetalle = totalDetalle;
    }
    public BigDecimal getPrecioRealUnidad() {
        return this.precioRealUnidad;
    }
    
    public void setPrecioRealUnidad(BigDecimal precioRealUnidad) {
        this.precioRealUnidad = precioRealUnidad;
    }




}


