package Model;
// Generated 16-jul-2017 13:53:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String cedula;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String celular;
     private String email;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public Empleado() {
    }

	
    public Empleado(String cedula) {
        this.cedula = cedula;
    }
    public Empleado(String cedula, String nombres, String apellidos, String direccion, String celular, String email, Set<Servicio> servicios) {
       this.cedula = cedula;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.celular = celular;
       this.email = email;
       this.servicios = servicios;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


