package Model;
// Generated 12-sep-2017 18:01:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private BigDecimal codfactura;
     private Vendedor vendedor;
     private Cliente cliente;
     private BigDecimal totalVenta;
     private Date fechaRegistro;
     private Character anulada;
     private Set<Comision> comisions = new HashSet<Comision>(0);
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Factura() {
    }

	
    public Factura(BigDecimal codfactura) {
        this.codfactura = codfactura;
    }
    public Factura(BigDecimal codfactura, Vendedor vendedor, Cliente cliente, BigDecimal totalVenta, Date fechaRegistro, Character anulada, Set<Comision> comisions, Set<DetalleFactura> detalleFacturas) {
       this.codfactura = codfactura;
       this.vendedor = vendedor;
       this.cliente = cliente;
       this.totalVenta = totalVenta;
       this.fechaRegistro = fechaRegistro;
       this.anulada = anulada;
       this.comisions = comisions;
       this.detalleFacturas = detalleFacturas;
    }
   
    public BigDecimal getCodfactura() {
        return this.codfactura;
    }
    
    public void setCodfactura(BigDecimal codfactura) {
        this.codfactura = codfactura;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public BigDecimal getTotalVenta() {
        return this.totalVenta;
    }
    
    public void setTotalVenta(BigDecimal totalVenta) {
        this.totalVenta = totalVenta;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Character getAnulada() {
        return this.anulada;
    }
    
    public void setAnulada(Character anulada) {
        this.anulada = anulada;
    }
    public Set<Comision> getComisions() {
        return this.comisions;
    }
    
    public void setComisions(Set<Comision> comisions) {
        this.comisions = comisions;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


