package Model;
// Generated 20-jul-2017 12:11:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private long codigo;
     private String codBarras;
     private String nombre;
     private String paquete;
     private BigDecimal precioCompra;
     private BigDecimal porcentajeDescuento;
     private BigDecimal precioCompraReal;
     private BigDecimal porcentajeUtilidad;
     private BigDecimal precioVentaReal;
     private Long stockMinUni;
     private Long stockActUni;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Producto() {
    }

	
    public Producto(long codigo) {
        this.codigo = codigo;
    }
    public Producto(long codigo, String codBarras, String nombre, String paquete, BigDecimal precioCompra, BigDecimal porcentajeDescuento, BigDecimal precioCompraReal, BigDecimal porcentajeUtilidad, BigDecimal precioVentaReal, Long stockMinUni, Long stockActUni, Set<DetalleFactura> detalleFacturas) {
       this.codigo = codigo;
       this.codBarras = codBarras;
       this.nombre = nombre;
       this.paquete = paquete;
       this.precioCompra = precioCompra;
       this.porcentajeDescuento = porcentajeDescuento;
       this.precioCompraReal = precioCompraReal;
       this.porcentajeUtilidad = porcentajeUtilidad;
       this.precioVentaReal = precioVentaReal;
       this.stockMinUni = stockMinUni;
       this.stockActUni = stockActUni;
       this.detalleFacturas = detalleFacturas;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public String getCodBarras() {
        return this.codBarras;
    }
    
    public void setCodBarras(String codBarras) {
        this.codBarras = codBarras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(String paquete) {
        this.paquete = paquete;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public BigDecimal getPorcentajeDescuento() {
        return this.porcentajeDescuento;
    }
    
    public void setPorcentajeDescuento(BigDecimal porcentajeDescuento) {
        this.porcentajeDescuento = porcentajeDescuento;
    }
    public BigDecimal getPrecioCompraReal() {
        return this.precioCompraReal;
    }
    
    public void setPrecioCompraReal(BigDecimal precioCompraReal) {
        this.precioCompraReal = precioCompraReal;
    }
    public BigDecimal getPorcentajeUtilidad() {
        return this.porcentajeUtilidad;
    }
    
    public void setPorcentajeUtilidad(BigDecimal porcentajeUtilidad) {
        this.porcentajeUtilidad = porcentajeUtilidad;
    }
    public BigDecimal getPrecioVentaReal() {
        return this.precioVentaReal;
    }
    
    public void setPrecioVentaReal(BigDecimal precioVentaReal) {
        this.precioVentaReal = precioVentaReal;
    }
    public Long getStockMinUni() {
        return this.stockMinUni;
    }
    
    public void setStockMinUni(Long stockMinUni) {
        this.stockMinUni = stockMinUni;
    }
    public Long getStockActUni() {
        return this.stockActUni;
    }
    
    public void setStockActUni(Long stockActUni) {
        this.stockActUni = stockActUni;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


