package Model;
// Generated 16-jul-2017 13:53:14 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String codbarras;
     private String nombreProducto;
     private BigDecimal precioVenta;
     private Long stockMinimo;
     private Long stockActual;
     private BigDecimal precioCompra;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Producto() {
    }

	
    public Producto(String codbarras) {
        this.codbarras = codbarras;
    }
    public Producto(String codbarras, String nombreProducto, BigDecimal precioVenta, Long stockMinimo, Long stockActual, BigDecimal precioCompra, Set<DetalleFactura> detalleFacturas) {
       this.codbarras = codbarras;
       this.nombreProducto = nombreProducto;
       this.precioVenta = precioVenta;
       this.stockMinimo = stockMinimo;
       this.stockActual = stockActual;
       this.precioCompra = precioCompra;
       this.detalleFacturas = detalleFacturas;
    }
   
    public String getCodbarras() {
        return this.codbarras;
    }
    
    public void setCodbarras(String codbarras) {
        this.codbarras = codbarras;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Long getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(Long stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public Long getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(Long stockActual) {
        this.stockActual = stockActual;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


