package Model;
// Generated 26-jul-2017 17:58:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private BigDecimal codigo;
     private String codBarras;
     private String nombre;
     private String paquete;
     private BigDecimal precioCompra;
     private BigDecimal porcentajeDescuento;
     private BigDecimal precioCompraReal;
     private BigDecimal porcentajeUtilidad;
     private BigDecimal precioVentaReal;
     private Long stockMinUni;
     private Long stockActUni;
     private BigDecimal comision;
     private BigDecimal ventaSugerida;
     private BigDecimal porcentajeComision;
     private Long unidadXPaquete;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Producto() {
    }

	
    public Producto(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Producto(BigDecimal codigo, String codBarras, String nombre, String paquete, BigDecimal precioCompra, BigDecimal porcentajeDescuento, BigDecimal precioCompraReal, BigDecimal porcentajeUtilidad, BigDecimal precioVentaReal, Long stockMinUni, Long stockActUni, BigDecimal comision, BigDecimal ventaSugerida, BigDecimal porcentajeComision, Long unidadXPaquete, Set<DetalleFactura> detalleFacturas) {
       this.codigo = codigo;
       this.codBarras = codBarras;
       this.nombre = nombre;
       this.paquete = paquete;
       this.precioCompra = precioCompra;
       this.porcentajeDescuento = porcentajeDescuento;
       this.precioCompraReal = precioCompraReal;
       this.porcentajeUtilidad = porcentajeUtilidad;
       this.precioVentaReal = precioVentaReal;
       this.stockMinUni = stockMinUni;
       this.stockActUni = stockActUni;
       this.comision = comision;
       this.ventaSugerida = ventaSugerida;
       this.porcentajeComision = porcentajeComision;
       this.unidadXPaquete = unidadXPaquete;
       this.detalleFacturas = detalleFacturas;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public String getCodBarras() {
        return this.codBarras;
    }
    
    public void setCodBarras(String codBarras) {
        this.codBarras = codBarras;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(String paquete) {
        this.paquete = paquete;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public BigDecimal getPorcentajeDescuento() {
        return this.porcentajeDescuento;
    }
    
    public void setPorcentajeDescuento(BigDecimal porcentajeDescuento) {
        this.porcentajeDescuento = porcentajeDescuento;
    }
    public BigDecimal getPrecioCompraReal() {
        return this.precioCompraReal;
    }
    
    public void setPrecioCompraReal(BigDecimal precioCompraReal) {
        this.precioCompraReal = precioCompraReal;
    }
    public BigDecimal getPorcentajeUtilidad() {
        return this.porcentajeUtilidad;
    }
    
    public void setPorcentajeUtilidad(BigDecimal porcentajeUtilidad) {
        this.porcentajeUtilidad = porcentajeUtilidad;
    }
    public BigDecimal getPrecioVentaReal() {
        return this.precioVentaReal;
    }
    
    public void setPrecioVentaReal(BigDecimal precioVentaReal) {
        this.precioVentaReal = precioVentaReal;
    }
    public Long getStockMinUni() {
        return this.stockMinUni;
    }
    
    public void setStockMinUni(Long stockMinUni) {
        this.stockMinUni = stockMinUni;
    }
    public Long getStockActUni() {
        return this.stockActUni;
    }
    
    public void setStockActUni(Long stockActUni) {
        this.stockActUni = stockActUni;
    }
    public BigDecimal getComision() {
        return this.comision;
    }
    
    public void setComision(BigDecimal comision) {
        this.comision = comision;
    }
    public BigDecimal getVentaSugerida() {
        return this.ventaSugerida;
    }
    
    public void setVentaSugerida(BigDecimal ventaSugerida) {
        this.ventaSugerida = ventaSugerida;
    }
    public BigDecimal getPorcentajeComision() {
        return this.porcentajeComision;
    }
    
    public void setPorcentajeComision(BigDecimal porcentajeComision) {
        this.porcentajeComision = porcentajeComision;
    }
    public Long getUnidadXPaquete() {
        return this.unidadXPaquete;
    }
    
    public void setUnidadXPaquete(Long unidadXPaquete) {
        this.unidadXPaquete = unidadXPaquete;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


