package Model;
// Generated 20-jul-2017 12:11:25 by Hibernate Tools 4.3.1



/**
 * Reporte generated by hbm2java
 */
public class Reporte  implements java.io.Serializable {


     private long codigo;
     private String descripcion;

    public Reporte() {
    }

	
    public Reporte(long codigo) {
        this.codigo = codigo;
    }
    public Reporte(long codigo, String descripcion) {
       this.codigo = codigo;
       this.descripcion = descripcion;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


