package Model;
// Generated 26-jul-2017 17:58:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Reporte generated by hbm2java
 */
public class Reporte  implements java.io.Serializable {


     private BigDecimal codigo;
     private String descripcion;

    public Reporte() {
    }

	
    public Reporte(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Reporte(BigDecimal codigo, String descripcion) {
       this.codigo = codigo;
       this.descripcion = descripcion;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


