package Model;
// Generated 16-jul-2017 13:53:14 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private BigDecimal codigo;
     private Empleado empleado;
     private BigDecimal total;
     private BigDecimal gananciaEmpresa;
     private BigDecimal gananciaEmpleado;
     private String descripcion;
     private Date fechaRegistro;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Servicio() {
    }

	
    public Servicio(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Servicio(BigDecimal codigo, Empleado empleado, BigDecimal total, BigDecimal gananciaEmpresa, BigDecimal gananciaEmpleado, String descripcion, Date fechaRegistro, Set<DetalleFactura> detalleFacturas) {
       this.codigo = codigo;
       this.empleado = empleado;
       this.total = total;
       this.gananciaEmpresa = gananciaEmpresa;
       this.gananciaEmpleado = gananciaEmpleado;
       this.descripcion = descripcion;
       this.fechaRegistro = fechaRegistro;
       this.detalleFacturas = detalleFacturas;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public BigDecimal getGananciaEmpresa() {
        return this.gananciaEmpresa;
    }
    
    public void setGananciaEmpresa(BigDecimal gananciaEmpresa) {
        this.gananciaEmpresa = gananciaEmpresa;
    }
    public BigDecimal getGananciaEmpleado() {
        return this.gananciaEmpleado;
    }
    
    public void setGananciaEmpleado(BigDecimal gananciaEmpleado) {
        this.gananciaEmpleado = gananciaEmpleado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


