package Model;
// Generated 22-jul-2017 17:32:23 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private BigDecimal codtipo;
     private String descripcion;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Tipo() {
    }

	
    public Tipo(BigDecimal codtipo) {
        this.codtipo = codtipo;
    }
    public Tipo(BigDecimal codtipo, String descripcion, Set<Usuario> usuarios) {
       this.codtipo = codtipo;
       this.descripcion = descripcion;
       this.usuarios = usuarios;
    }
   
    public BigDecimal getCodtipo() {
        return this.codtipo;
    }
    
    public void setCodtipo(BigDecimal codtipo) {
        this.codtipo = codtipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


