package Model;
// Generated 20-jul-2017 12:11:25 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String cedula;
     private Tipo tipo;
     private String password;
     private String email;
     private String validado;
     private String codregistro;
     private Vendedor vendedor;

    public Usuario() {
    }

	
    public Usuario(String cedula) {
        this.cedula = cedula;
    }
    public Usuario(String cedula, Tipo tipo, String password, String email, String validado, String codregistro, Vendedor vendedor) {
       this.cedula = cedula;
       this.tipo = tipo;
       this.password = password;
       this.email = email;
       this.validado = validado;
       this.codregistro = codregistro;
       this.vendedor = vendedor;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getValidado() {
        return this.validado;
    }
    
    public void setValidado(String validado) {
        this.validado = validado;
    }
    public String getCodregistro() {
        return this.codregistro;
    }
    
    public void setCodregistro(String codregistro) {
        this.codregistro = codregistro;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }




}


